"""Initial migration.

Revision ID: c4d85546587e
Revises: 
Create Date: 2021-04-13 11:38:55.785618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4d85546587e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'os',
               existing_type=postgresql.ENUM('android', 'ios', name='os'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'os',
               existing_type=postgresql.ENUM('android', 'ios', name='os'),
               nullable=False)
    # ### end Alembic commands ###
